#!/usr/bin/env bash

# useage:
#
# Archive a database to /tmp/.
#   mysqlarchive -uroot -B dbname
#
# Archive a database and put to dropbox.
#   mysqlarchive -uroot -B dbname | xargs ibackup_dropbox.py
#
# If you don't want mysqldump generate 'USE dbname' statement, use:
#   mysqlarchive dbname -uroot 
# Without -B or --databases option and dbname must be the first argument.



NOW=$(date +"%Y%m%d-%H%M%S")
DATABASES=""


while getopts ":B:" opt; do
    case $opt in
        B)
            DATABASES=$OPTARG
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

if [[ -z "$DATABASES" ]]; then
    DATABASES=$1
fi

OUTFILE=/tmp/$DATABASES-$NOW.sql.bz2

mysqldump $@ | bzip2 > $OUTFILE
echo $OUTFILE
