#!/usr/bin/env bash

# useage:
#
# Archive a database to /tmp/.
#   mysqlarchive -uroot -B dbname
#
# Archive a database and put to dropbox.
#   mysqlarchive -uroot -B dbname | ibackup_dropbox.py


NOW=$(date +"%Y%m%d-%H%M%S")
DATABASES=""

while getopts ":B:" opt; do
    case $opt in
        B)
            DATABASES=$OPTARG
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

OUTFILE=/tmp/$DATABASES-$NOW.sql.bz2

mysqldump $@ | bzip2 > $OUTFILE
echo $OUTFILE
